### ISSUE TITLE
Changing text direction around a path

### ISSUE THREAD

**Issue by ghost** [tex-xet/bidi#16]
Currently, there is no way to change the text direction around a path.

````latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{decorations.text}
\usepackage{bidi}
\begin{document}
\begin{tikzpicture}
\path [postaction={decorate,decoration={raise=-1ex,text along path, text align=center,
text={|\huge|This is a test to write around a circle}}}] (0,0) circle (2);
\end{tikzpicture}
\end{document}
````

This question was originally posted [here](http://qa.parsilatex.com/10048).

**Comment by vafa** [comment]
`tikz` provides a way to achieve this already. See [this question and answer](https://tex.stackexchange.com/questions/410820).
