### ISSUE TITLE
bidishadowtext and newlines

### ISSUE THREAD

**Issue by ambs** [tex-xet/bidi#48]
Hi,
First, sorry to post a question here, but I noticed there is a tag for questions, so hopefully that is acceptable.
Also, sorry to post a question about bidishadowtext, but @vafa's repository no longer exists, and I noticed he is a contributor here. 
I am trying to use bidishadowtext in a macro, and I need to allow the macro users to enter multi-line text. The problem is that bidishadowtext does't like `\\` or `\cr` commands.
Is there any way to make it work?
Thanks.

**Comment by vafa** [comment]
Can you provide a minimal example?

**Comment by ambs** [comment]
Well, this does not complain, but doesn't work either:

````````````
\documentclass{article}

\usepackage{bidishadowtext}
\usepackage{bidi}

\begin{document}
\bidishadowtext{Text\\Text}

\end{document}
``````````

In my specific case I get the common `\item` missing, but probably because it is being used inside a Tikz. Meanwhile I'll try to get an example nearer to my current code. Thanks

**Comment by ambs** [comment]
And now with the correct error message I am getting:

```
\documentclass{article}
\usepackage{tikz}
\usepackage{bidishadowtext}
\usepackage{bidi}
\begin{document}
\begin{tikzpicture}
\node [align=flush right, text width=1cm] at (1.0,1.0) { \bidishadowtext{Text\\Text}};
\end{tikzpicture}
\end{document}

```

**Comment by vafa** [comment]
The command `\bidishadowtext` can only contain short argument; if you want to give it a long argument, then you would need to use `\parbox`.

**Comment by ambs** [comment]
Ah, trying to find the correct values of position for parbox.
Thanks

**Comment by vafa** [comment]
I now accept donations to the bidi package. Anyone can donate any amount to the bidi package using [My PayPal.Me](https://www.paypal.me/persiantex).

The donations allow me to spend more time working on the bidi package and make it even better. If you know that some other people may also be interested in donating to the bidi package development, please let them know.
