### ISSUE TITLE
biditufte-book error : Undefined control sequence. \LTRcite  

### ISSUE THREAD

**Issue by jalilsadati** [tex-xet/bidi#51]
Dear Vafa,

By runing this code:
```latex
\documentclass{biditufte-book}
\usepackage{ptext}
 \usepackage{xepersian}
\settextfont{XB Niloofar}
\begin{document} 
\chapter{نمونه مثال از طبقه نوشتاری\\ \lr{biditufte-book}}
مقداری متن معمولی...
\sidenote[][5mm]{ \ptext[1]}
\ptext[4]
\footnote{آیا این زیرنویس در حاشیه خواهد بود؟}
و چند مرجع...
\LTRcite{Amintoosi09video}
\cite{Amintoosi87afzayesh}
\bibliography{MyReferences}
\bibliographystyle{plainnat-fa}
\end{document}
```

we have a pdf that is ok but with this error:

``` latex
undefined control sequence. \LTRcite{Amintoosi09video} 
```
Unfortunately I could not add a label to this post and  my minimal example file even with ZIP extension.
I refer to this link for my file:

[http://qa.parsilatex.com/24157/](url)

**Comment by vafa** [comment]
Is your TeX distribution up to date? What is your version of the `bidi` package? I get no error with version 30 of the `bidi` package.

**Comment by jalilsadati** [comment]
Thanks. The problem was solved by update texlive.
