### ISSUE TITLE
Using extrafootnotefeatures and computeautoilg with 12pt option causes Arithmetic overflow.! 

### ISSUE THREAD

**Issue by javadr** [tex-xet/bidi#52]
When I try to compile the code below I get Arithmetic overflow.!
This problem only available when the defualt font size of the text set to 12pt whereas there are no issues with 10pt or 11pt. 

```latex
\documentclass[12pt]{article}

\usepackage[extrafootnotefeatures=on,computeautoilg=on]{xepersian}
\settextfont{Yas}

\paragraphfootnotes

\begin{document}
Hi 
\end{document}
```

the following error will be shown 
```bash
! Arithmetic overflow.
\paragraphfootnotes ...\multiply \dimen 0 by 1024
                                                  \divide \dimen 0 by \hsize...
l.6 \paragraphfootnotes
```

**Comment by vafa** [comment]
Oh! This is natural. The last paragraph (dangerous bend sign) on page 58 of the TeXbook states that
> TeX will not deal with dimensions whose absolute value is 2^{30}sp or more. In other words, the maximum legal dimension is slightly less than 16384pt. 

LaTeX sets the `\maxdimen` to `16383.99999pt`. When you use `computeautoilg` in your TeX document, the `\baselineskip` will be increased to `20.94725pt`. Now multiply this by `1024` which is larger than `\maxdimen` and so you get `Arithmetic overflow` error.

Anyway, I will fix it when I have time but unfortunately that is not now.

**Comment by vafa** [comment]
I will push version 30.2 of the bidi package to CTAN which should fix this issue.

**Comment by javadr** [comment]
thanks.
