### ISSUE TITLE
RTL text center aligned rather then right aligned with beamer 

### ISSUE THREAD

**Issue by seloumi** [tex-xet/bidi#53]
Consider this piece of code 

```
\documentclass{beamer}
\usepackage{fontspec}
\usepackage{bidi}

\setsansfont[Script=Arabic]{Amiri}

\begin{document}

\begin{frame}
\setRTL
السلام عليكم
\par
\end{frame}

\begin{frame}
Hello world
\end{frame}

\end{document}

```

Why text on the first frame is center aligned, and how can fix this issue to obtain text right aligned. thanks in advance.

**Comment by vafa** [comment]
Beamer uses `\raggedright` for pure left to right text. You need `\raggedleft` when the paragraph is typeset right to left.

**Comment by vafa** [comment]
I now accept donations to the bidi package. Anyone can donate any amount to the bidi package using [My PayPal.Me](https://www.paypal.me/persiantex).

The donations allow me to spend more time working on the bidi package and make it even better. If you know that some other people may also be interested in donating to the bidi package development, please let them know.
