### ISSUE TITLE
Inverted hebrew in math mode

### ISSUE THREAD

**Issue by ohadlb** [tex-xet/bidi#54]
Hebrew text in math mode compiles with inverted word order. When I use an old version of bidi (v15.7, 2014/09/25) the text displays correctly. Here is a test file (using polyglossia):
```
\documentclass{article}

\usepackage{amsmath}
\usepackage{polyglossia}
\setmainlanguage{hebrew}
\newfontfamily{\hebrewfont}[Script=Hebrew,Ligatures=TeX]{David CLM}

\begin{document}
$\pi(n) = \#\{\text{$p$ מספר ראשוני שאינו גדול מ־$n$}\}$
\end{document}
```

**Comment by vafa** [comment]
This is a bug of `polyglossia`. You can put `\setnonlatin` after loading `polyglossia` to fix this. You also have `\setlatin` to get back to the default behavior.

**Comment by vafa** [comment]
I now accept donations to the bidi package. Anyone can donate any amount to the bidi package using [My PayPal.Me](https://www.paypal.me/persiantex).

The donations allow me to spend more time working on the bidi package and make it even better. If you know that some other people may also be interested in donating to the bidi package development, please let them know.
