### ISSUE TITLE
\amstext@ in amstext-xetex-bidi.def nevers sets text RTL.

### ISSUE THREAD

**Issue by dcpurton** [tex-xet/bidi#59]
I think there is a bug in the definition of `\amstext@` in `amstext-xetex-bidi.def`. It uses `\if@nonlatin` as the test for setting `\beginR` and `\endR`, but it seems that `\if@nonlatin` is *always* false. So, any text inside `$\text{…}$` is always set LTR even in a RTL document. Using `\if@RTL` as the test seems to work OK.

This came up while I was looking at https://tex.stackexchange.com/questions/362295/hebrew-text-in-math-mode

**MWE:**

```TeX
\documentclass{article}

\usepackage{amsmath}
\usepackage{bidi}

\pagestyle{empty}

\begin{document}

This should be LTR, and it is.

$\text{This should be LTR, and it is.}$

\setRTL

This should be RTL, and it is.

$\text{This should be RTL, but it's not.}$

\makeatletter
\def\textdef@#1#2#3{\hbox{{%
                    \everymath{#1}%
                    \let\f@size#2\selectfont
                    \if@RTL\beginR\fi#3\if@RTL\endR\fi}}}
\makeatother

\setLTR

This should be LTR, and it is.

$\text{This should be LTR, and it is.}$

\setRTL

This should be RTL, and it is.

$\text{This should be RTL, and it is.}$

\end{document}
```

![temp04](https://user-images.githubusercontent.com/6268044/33231917-46559796-d24d-11e7-9429-77600eea0865.png)

**Comment by vafa** [comment]
There is no bug.

**Comment by dcpurton** [comment]
So what is the point of the `\if@nonlatin` test? Nothing sets it to true.

**Comment by vafa** [comment]
It is a boolean provided so higher-level packages set them to true in non-latin scripts and false in latin scripts (for instance, look at `xepersian`). In your case, that is a `polyglossia` bug which have been reported to its author several times but have not been fixed yet.

**Comment by dcpurton** [comment]
OK, thanks. I think I get the difference between `\if@RTL` and `\if@nonlatin`.

So, just to be clear, your advice would be to patch `polyglossia` something like this? (Presumably this could potentially break existing documents, though.)

```TeX
\apptocmd{\select@@language}
  {\ifcsundef{setRL}
     {}
     {\iftoggle{#1@latin}{\@nonlatinfalse}{\@nonlatintrue}}}
  {}
  {}
```

**Comment by vafa** [comment]
I now accept donations to the bidi package. Anyone can donate any amount to the bidi package using [My PayPal.Me](https://www.paypal.me/persiantex).

The donations allow me to spend more time working on the bidi package and make it even better. If you know that some other people may also be interested in donating to the bidi package development, please let them know.
